### ISSUE TITLE
How to change the shell from ZSH to Bash / TCSH?

### ISSUE THREAD

**Issue by justrajdeep** [gu-fan/simpleterm.vim#2]
Hi 

How to change the shell from ZSH to Bash / TCSH?

- Rajdeep

**Comment by gu-fan** [comment]
`set shell=/bin/zsh`

should be set after plugin loaded

well, remove the setting in plugin, put it in your vimrc

**Comment by gu-fan** [comment]
add this to document

**Comment by justrajdeep** [comment]
Thanks
