### ISSUE TITLE
Sline in Windows

### ISSUE THREAD

**Issue by jmpicaza** [gu-fan/simpleterm.vim#3]
![image](https://user-images.githubusercontent.com/2660543/42372495-9fe67e64-8112-11e8-8e97-daf8df0f670e.png)

1st: Thanks a lot for the plugin. Its great!

¿some problem with encoding or something?

**Comment by jmpicaza** [comment]
Fixed changing
```
    "call term_sendkeys(last, "\<C-W>".a:cmd."\<CR>")
    call term_sendkeys(last, a:cmd."\<CR>")
```
and
 ```
       "call term_sendkeys(buf, "\<C-W>".a:cmd."\<CR>")
        call term_sendkeys(buf, a:cmd."\<CR>")
```

Thanks again

**Comment by gu-fan** [comment]
ok, remove that, I want to prevent previous types but seems useless
