### ISSUE TITLE
Multiple terminal windows

### ISSUE THREAD

**Issue by linqiaozhi** [gu-fan/simpleterm.vim#4]
This an excellent plugin, thanks for making it!

I often have multiple terminals open, say, one for each tab. Is it possible to make it so that `:Sline` sends the line to the terminal that is in the same tab? Or perhaps the last used terminal? Right now, it seems to always send to the same terminal, regardless of whether or not other terminals exist.

**Comment by gu-fan** [comment]
d23714

**Comment by gu-fan** [comment]
d23714312767816793753c96c1a859da98b9545f

added Sbind

**Comment by linqiaozhi** [comment]
Sbind looks like exactly what I'm looking for, but I can't get it to work.

Suppose I have a terminal open in the first tab. I now go into a new tab and try opening a new terminal by using `:term`, and then calling Sbind in a different window (with the hope of binding that window to the new terminal), and all it does is give me the first one. I tried doing `Sbind terminal:<buffer number of new terminal>`, but it still binds to the old one.

**Comment by gu-fan** [comment]
create new one with `:Sadd`

**Comment by linqiaozhi** [comment]
Wow man, this is really solid...nicely done! Thanks for making the feature so quickly.

**Comment by gu-fan** [comment]
yes,  thanks
